name: 'Build & Test'

on:
  push:
    branches: [ main, develop, support/* ]
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.asciidoc'
  pull_request:
    branches: [ main, develop, support/* ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.asciidoc'
  workflow_dispatch:

jobs:
  linux-build:
    strategy:
      matrix:
        profile: [ "debug-x64", "release-x64" ]
    runs-on: ubuntu-latest

    env:
      PAKCAGE_CHANNEL: "unknown"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.3
      with:
        versionSpec: '5.x'

    - name: Create Build Image
      run: docker build scripts/docker -t buildimage -m 2GB

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v3.1.3

    - name: Development Channel
      run: echo "PAKCAGE_CHANNEL=alpha" >> $GITHUB_ENV
      if: github.ref == 'refs/heads/develop'

    - name: Pre-release Channel
      run: echo "PAKCAGE_CHANNEL=beta" >> $GITHUB_ENV
      if: startswith(github.ref, 'refs/heads/release/')

    - name: Release Channel
      run: echo "PAKCAGE_CHANNEL=stable" >> $GITHUB_ENV
      if: github.ref == 'refs/heads/main'

    - name: Build
      run: >-
        docker 
        run --rm 
        -v "$(pwd):/repo" 
        -w /repo 
        --name buildos buildimage 
        conan create . --user rajeshwarraja 
        --channel ${{env.PAKCAGE_CHANNEL}} 
        --version ${{env.GitVersion_MajorMinorPatch}}
        --profile:build=${{matrix.profile}}

    - name: Create Release Tag
      if: github.ref == 'refs/heads/main'
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        custom_tag: ${{env.GITVERSION_MAJORMINORPATCH}}

