name: 'Build & Test'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - 'doc/**'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Configure CMake
      run: cmake --preset="default"

    - name: Build
      run: cmake --build --preset="default"

    - name: Test
      run: ctest --preset="default"
